# Generated by Django 4.2.7 on 2024-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_publication_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publication_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slogan',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
