# Generated by Django 4.2.7 on 2024-06-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categorys',
        ),
    ]
