# Generated by Django 4.2.7 on 2024-06-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
