# Generated by Django 4.2.7 on 2024-06-21 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
