# Generated by Django 4.2.7 on 2024-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_post_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
